language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

install:
  - pip install git+git://github.com/mitsuhiko/werkzeug.git#egg=Werkzeug
  - pip install --editable .

script: make test

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
